# Generated by Django 3.0.2 on 2021-02-16 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercice', '0018_auto_20210208_1032'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(blank=True, max_length=60, null=True)),
                ('repetitions', models.CharField(blank=True, max_length=60, null=True)),
                ('sets', models.CharField(blank=True, max_length=60, null=True)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercice.Exercice')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.Training')),
            ],
        ),

        migrations.RemoveField(
            model_name='training',
            name='exercices',
        ),
        migrations.AddField(
            model_name='training',
            name='exercices',
            field=models.ManyToManyField(blank=True, through='training.Difficulty', to='exercice.Exercice'),
        ),
    ]
