# Generated by Django 3.0.2 on 2021-02-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercice', '0018_auto_20210208_1032'),
        ('training', '0003_auto_20210216_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='exercices_list',
        ),
        migrations.AddField(
            model_name='training',
            name='exercices',
            field=models.ManyToManyField(blank=True, to='exercice.Exercice'),
        ),
    ]
