# Generated by Django 3.0.2 on 2021-02-16 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_auto_20210216_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='exercices',
        ),
    ]
