# Generated by Django 3.0.2 on 2021-02-16 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_training_exercices'),
    ]

    operations = [
    ]
