# Generated by Django 3.0.2 on 2021-02-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercice', '0018_auto_20210208_1032'),
        ('training', '0009_auto_20210216_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='exercices',
        ),
        migrations.AddField(
            model_name='training',
            name='exercices',
            field=models.ManyToManyField(through='training.Difficulty', to='exercice.Exercice'),
        ),
    ]
