# Generated by Django 3.0.2 on 2021-02-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_auto_20210217_0006'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='difficulty',
            name='repetitions',
        ),
        migrations.AddField(
            model_name='difficulty',
            name='repetitions',
            field=models.CharField(default=2, max_length=60),
            preserve_default=False,
        ),

        migrations.RemoveField(
            model_name='difficulty',
            name='duration',
        ),
        migrations.AddField(
            model_name='difficulty',
            name='duration',
            field=models.CharField(default='test', max_length=60),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='difficulty',
            name='sets',
        ),
        migrations.AddField(
            model_name='difficulty',
            name='sets',
            field=models.CharField(default=5, max_length=60),
            preserve_default=False,
        ),
    ]
