# Generated by Django 3.0.2 on 2021-02-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercice', '0018_auto_20210208_1032'),
        ('training', '0011_auto_20210217_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='exercices',
            field=models.ManyToManyField(through='training.Difficulty', to='exercice.Exercice'),
        ),
    ]
