# Generated by Django 3.0.2 on 2021-02-19 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercice', '0018_auto_20210208_1032'),
        ('training', '0014_auto_20210219_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='exercices',
            new_name='difficulties',
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='exercice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exers', to='exercice.Exercice'),
        ),
    ]
