# Generated by Django 3.0.2 on 2021-02-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_auto_20210219_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='exercices',
        ),
    ]
