# Generated by Django 3.0.2 on 2021-02-19 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercice', '0018_auto_20210208_1032'),
        ('training', '0016_remove_training_exercices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficulty',
            name='exercice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercice.Exercice'),
        ),
        migrations.AlterField(
            model_name='training',
            name='difficulties',
            field=models.ManyToManyField(related_name='exers', through='training.Difficulty', to='exercice.Exercice'),
        ),
    ]
