# Generated by Django 3.0.2 on 2021-02-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0020_auto_20210219_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='difficulty',
            name='ex_id',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
