# Generated by Django 3.0.2 on 2021-01-25 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_favorites'),
        ('exercice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercice',
            name='categories',
        ),
        migrations.AlterField(
            model_name='exercice',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exers', to='profiles.Profile'),
        ),
    ]
