# Generated by Django 3.0.2 on 2021-01-25 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercice', '0005_auto_20210125_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='exercice',
            name='categories',
            field=models.ForeignKey(blank=True, default=12, on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories', to='exercice.Category'),
        ),
    ]
