# Generated by Django 3.0.2 on 2021-01-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210125_1052'),
        ('exercice', '0006_auto_20210125_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercice',
            name='categories',
        ),
        migrations.AddField(
            model_name='exercice',
            name='categories',
            field=models.ManyToManyField(related_name='categoriess', to='category.Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
