# Generated by Django 3.0.2 on 2021-01-26 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercice', '0008_auto_20210125_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercice',
            name='categories',
        ),
    ]
