# Generated by Django 3.0.2 on 2021-02-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20210125_1052'),
        ('exercice', '0011_auto_20210202_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='categories',
            field=models.ManyToManyField(blank=True, to='category.Category'),
        ),
    ]
