# Generated by Django 3.0.2 on 2021-03-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210212_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.TextField(blank=True, default='https://avatars.dicebear.com/api/avataaars/YSVI8592G.svg'),
        ),
    ]
